server:
  port: 8081


spring:
  application:
    name: acis-alerts
  datasource:
    url: jdbc:postgresql://localhost:5432/acis?options=-c%20timezone=UTC
    username: acis
    password: acis_dev_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: acis-alerts-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/acis

logging:
  level:
    com.netcradus.acis: DEBUG
