server:
  port: 8087


spring:
  application:
    name: acis-threat-service
  datasource:
    url: jdbc:postgresql://localhost:5432/acis?options=-c%20timezone=UTC
    username: acis
    password: acis_dev_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/acis

logging:
  level:
    com.netcradus.acis: DEBUG

grpc:
  client:
    aiService:
      address: 'static://127.0.0.1:50051'
      negotiation-type: plaintext
