package com.netcradus.acis.soar.support;

import com.netcradus.acis.common.apikey.ApiKey;
import com.netcradus.acis.common.apikey.ApiKeyRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.time.OffsetDateTime;
import java.util.HexFormat;
import java.util.UUID;

/**
 * Real ApiKey issuance, shared by SettingsController (user-generated keys,
 * Settings > API Keys) and every vendor-integration controller that needs a
 * key of its own to call /api/ingest/external/json on the tenant's behalf
 * (see IntegrationPollerService). Same 40-char random token + SHA-256 hash
 * scheme in both cases — issued system keys are ordinary rows in api_keys,
 * visible and revocable by the tenant like any key they generated by hand.
 */
@Component
@RequiredArgsConstructor
public class ApiKeyIssuer {

    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    private static final String CHARS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

    private final ApiKeyRepository apiKeyRepository;

    public record Issued(ApiKey key, String rawToken) {}

    public Issued issue(UUID tenantId, String keyName, String role) {
        String rawToken = generateRandomToken();
        ApiKey key = new ApiKey();
        key.setTenantId(tenantId);
        key.setKeyName(keyName);
        key.setRole(role);
        key.setTokenHash(hashToken(rawToken));
        key.setTokenPreview(rawToken.substring(rawToken.length() - 4));
        key.setCreatedAt(OffsetDateTime.now());
        key.setStatus("Active");
        ApiKey saved = apiKeyRepository.save(key);
        return new Issued(saved, rawToken);
    }

    public String generateRandomToken() {
        StringBuilder sb = new StringBuilder("acis_live_");
        for (int i = 0; i < 40; i++) {
            sb.append(CHARS.charAt(SECURE_RANDOM.nextInt(CHARS.length())));
        }
        return sb.toString();
    }

    public String hashToken(String rawToken) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(rawToken.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hash);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }
}
