package com.netcradus.acis.platformadmin.audit;

public enum AuditAction {
    USER_CREATED, USER_UPDATED, USER_DELETED,
    USER_ACTIVATED, USER_DEACTIVATED,
    PASSWORD_RESET, TEMP_PASSWORD_SET,
    PASSWORD_CHANGE_REQUIRED, PASSWORD_RESET_EMAIL_SENT,
    ACCOUNT_LOCKED, ACCOUNT_UNLOCKED, BRUTE_FORCE_CLEARED,
    MFA_REQUIRED, MFA_REMOVED, MFA_RESET,
    ROLE_ASSIGNED, ROLE_REMOVED,
    USER_MOVED_TENANT,
    SESSION_TERMINATED, ALL_SESSIONS_TERMINATED,
    TENANT_CREATED, TENANT_UPDATED, TENANT_SUSPENDED,
    TENANT_REACTIVATED, TENANT_DELETED,
    TENANT_PLAN_CHANGED, TENANT_MODULES_CHANGED
}
