  # -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: acis_ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'acis_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\racis_ai.proto\x12\x07\x61\x63is.ai\"3\n\x10\x45nrichIocRequest\x12\x11\n\tindicator\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"e\n\x11\x45nrichIocResponse\x12\x11\n\tindicator\x18\x01 \x01(\t\x12\x14\n\x0cthreat_score\x18\x02 \x01(\x05\x12\x12\n\ncategories\x18\x03 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t2X\n\x12ThreatIntelService\x12\x42\n\tEnrichIoc\x12\x19.acis.ai.EnrichIocRequest\x1a\x1a.acis.ai.EnrichIocResponseB+\n\x1a\x63om.netcradus.acis.ai.grpcB\x0b\x41\x63isAiProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'acis_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.netcradus.acis.ai.grpcB\013AcisAiProtoP\001'
  _globals['_ENRICHIOCREQUEST']._serialized_start=26
  _globals['_ENRICHIOCREQUEST']._serialized_end=77
  _globals['_ENRICHIOCRESPONSE']._serialized_start=79
  _globals['_ENRICHIOCRESPONSE']._serialized_end=180
  _globals['_THREATINTELSERVICE']._serialized_start=182
  _globals['_THREATINTELSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
