package com.netcradus.acis.soar.controller;

import com.netcradus.acis.common.dto.ApiResponse;
import com.netcradus.acis.soar.model.AuditEntry;
import com.netcradus.acis.soar.service.ComplianceService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/compliance")
@RequiredArgsConstructor
public class ComplianceController {

    private final ComplianceService complianceService;

    /** X-Tenant-ID is always JWT-derived, never client-supplied — required so a dropped header can never leak another tenant's data. */
    private UUID resolveTenant(UUID tenantId) {
        if (tenantId == null) {
            throw new IllegalStateException("X-Tenant-ID missing; request should have been rejected upstream");
        }
        return tenantId;
    }

    @GetMapping("/posture")
    public ApiResponse<List<ComplianceService.ComplianceFramework>> getCompliancePosture(
            @RequestHeader(value = "X-Tenant-ID", required = false) UUID tenantId
    ) {
        return ApiResponse.success(complianceService.getFrameworks(resolveTenant(tenantId)));
    }

    @GetMapping("/audit-trail")
    public ApiResponse<List<AuditEntry>> getAuditTrail(
            @RequestHeader(value = "X-Tenant-ID", required = false) UUID tenantId
    ) {
        return ApiResponse.success(complianceService.getAuditTrail(resolveTenant(tenantId)));
    }

    /** Real tamper-evidence check - recomputes the actual hash chain rather than trusting a stored status flag. See ComplianceService.verifyAuditChain. */
    @GetMapping("/audit-trail/verify")
    public ApiResponse<ComplianceService.ChainVerificationResult> verifyAuditTrail(
            @RequestHeader(value = "X-Tenant-ID", required = false) UUID tenantId
    ) {
        return ApiResponse.success(complianceService.verifyAuditChain(resolveTenant(tenantId)));
    }

    @GetMapping("/report")
    public ApiResponse<Map<String, String>> generateComplianceReport(
            @RequestHeader(value = "X-Tenant-ID", required = false) UUID tenantId) {
        resolveTenant(tenantId);
        return ApiResponse.success(Map.of(
            "message", "Compliance report generation queued successfully.",
            "downloadUrl", "/api/compliance/report/download"
        ));
    }

    @GetMapping("/report/download")
    public ResponseEntity<byte[]> downloadComplianceReport(
            @RequestHeader(value = "X-Tenant-ID", required = false) UUID tenantId) {
        UUID tenant = resolveTenant(tenantId);
        List<ComplianceService.ComplianceFramework> frameworks = complianceService.getFrameworks(tenant);

        StringBuilder report = new StringBuilder("ACIS Compliance Report\n\n");
        for (ComplianceService.ComplianceFramework framework : frameworks) {
            report.append("== ").append(framework.getName()).append(" (").append(framework.getDescription())
                    .append(") — ").append(framework.getPercentage()).append("% ==\n");
            for (ComplianceService.ComplianceControl control : framework.getControls()) {
                report.append("  - ").append(control.name()).append(": ").append(control.count())
                        .append(" (").append(control.status()).append(")\n");
            }
            report.append("\n");
        }
        report.append("Audit entries: ").append(complianceService.getAuditTrail(tenant).size()).append("\n\n");
        report.append("Report generated by ACIS compliance engine.");

        byte[] content = report.toString().getBytes(StandardCharsets.UTF_8);

        return ResponseEntity.ok()
            .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=acis-compliance-report.txt")
            .contentType(MediaType.TEXT_PLAIN)
            .body(content);
    }
}
