package com.netcradus.acis.soar.controller;

import com.netcradus.acis.common.dto.ApiResponse;
import com.netcradus.acis.soar.model.AuditEntry;
import com.netcradus.acis.soar.service.ComplianceService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/compliance")
@RequiredArgsConstructor
public class ComplianceController {

    private final ComplianceService complianceService;

    @GetMapping("/posture")
    public ApiResponse<List<ComplianceService.ComplianceFramework>> getCompliancePosture(
            @RequestHeader(value = "X-Tenant-ID", required = false) UUID tenantId
    ) {
        return ApiResponse.success(complianceService.getFrameworks(tenantId));
    }

    @GetMapping("/audit-trail")
    public ApiResponse<List<AuditEntry>> getAuditTrail(
            @RequestHeader(value = "X-Tenant-ID", required = false) UUID tenantId
    ) {
        return ApiResponse.success(complianceService.getAuditTrail(tenantId));
    }

    @GetMapping("/report")
    public ApiResponse<Map<String, String>> generateComplianceReport() {
        return ApiResponse.success(Map.of(
            "message", "Compliance report generation queued successfully.",
            "downloadUrl", "/api/compliance/report/download"
        ));
    }

    @GetMapping("/report/download")
    public ResponseEntity<byte[]> downloadComplianceReport() {
        String reportText = "ACIS Compliance Report\n\n" +
            "- NIS2 Posture: 92%\n" +
            "- GDPR Posture: 88%\n" +
            "- ISO 27001 Posture: 74%\n" +
            "- Audit entries: " + complianceService.getAuditTrail(null).size() + "\n\n" +
            "Report generated by ACIS compliance engine.";

        byte[] content = reportText.getBytes(StandardCharsets.UTF_8);

        return ResponseEntity.ok()
            .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=acis-compliance-report.txt")
            .contentType(MediaType.TEXT_PLAIN)
            .body(content);
    }
}
